import type { Metadata } from "next";
import { Imprima, Inter } from "next/font/google";
import "./globals.css";
import { Navbar2 } from "./componet/Nvbar2";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Al-jannat Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Navbar2/>
          </div>{children}</body>
    </html>
  );
}
